### ISSUE TITLE
Feature request: Add tarif meter

### ISSUE THREAD

**Issue by maartenhendrix** [hif2k1/battery_sim#1]
I have a meter with 2 tarifs and would like to be able to add those sensors so I don’t need to create a template. My meter has 2 tarifs for consumption and 2 for production.

**Comment by Vato9394** [comment]
This would be nice. Most households (in the benelux) have 1 tarif for day and 1 tarif for night.
If you can make it so that we can add multiple import_sensors and export_sensors, that would be great.

**Comment by hif2k1** [comment]
@YMGV I have added this feature to the latest build. It would be great if you could test it as I don't have a variable tariff set up so I can't easily see if it is working. Please let me know if it works for you. I'm not sure how to handle currency units and things so maybe you can advise if it's working. 

Many thanks

**Comment by ronaldt80** [comment]
Hi @hif2k1 - what would be the way to configure this? Can I just add 2 input and 2 export sensors?

To clarify, I have the same setup, at 23:00 and on weekends we are on tarriff 1 and at 7:00 on weekdays we switch to tariff 2. My smart meter reports this as 4 different kWh measurements, EG 2 times import and 2 times export.
