### ISSUE TITLE
Use statistics sensors that are not created by recorder integration

### ISSUE THREAD

**Issue by marcin478** [hif2k1/battery_sim#101]
I'm using [Tauron-AMIplus](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus) Home Assistant integration for `Energy` dashboard. This integration provides hourly statistics for consumed and generated energy. Unfortunately those sensors are not visible in the `Battery Simulation` integration as import/export sensor/meter.

I assume this is because Statistic ID name is different:

| Name | Statistic id | Statistics unit | Source | Issue |
| -------| ------------ | --------- | --------- | --------- |
Tauron AMIplus 123322415500468123 consumption | tauron_importer:123322415500468123_consumption | kWh | tauron_importer | No issue |
Tauron AMIplus 123322415500468123 generation | tauron_importer:123322415500468123_generation | kWh | tauron_importer | No issue |

Those statistics can be used by Statistics Graph card or `Energy` dashboard, but not in the `Battery Simulation`:
`User input malformed: Entity tauron_importer:123322415500468123_consumption is neither a valid entity ID nor a valid UUID for dictionary value @ data['import_sensor']`

**Comment by hif2k1** [comment]
Ah, yes that is an issue. You can still use the YAML setup in your home
assistant config as that doesn't limit the sensors you can select.
Alternatively you could use the GUI (graphical) setup that you have been
trying to use and select any other sensor that shows up and then edit the
conig file afterwards. It's called core.configentries and is in the hidden
.storage directory in your home assistant config directory.

**Comment by marcin478** [comment]
Thanks for the ideas! Both are good. Initially I was planning to fork the project and remove the constrain in the code.

**Comment by hif2k1** [comment]
Ok, sure. I think I'd like to keep it as is in the main branch because for
most users it makes setup much easier.

Thanks,

Hamish
