### ISSUE TITLE
enhacement: Reset battery at specific date

### ISSUE THREAD

**Issue by SyBeer** [hif2k1/battery_sim#102]
Hi, 

Many thanks for your work on this plugin.  

It's not a bug - it's a feature.
Is there any solution to reset battery on specific date i.e. end of June and end of December?

I have agreement with grid operator that assume reset battery on every half a year.

Best
Sybeer

**Comment by hif2k1** [comment]
No worries. There is a reset button so you would just need to create a
homeassistant automation that triggers that button at the time you want I
guess. Hope that works for you.

**Comment by SyBeer** [comment]
Thank you!
