### ISSUE TITLE
Question about warning on decreasing utility meter

### ISSUE THREAD

**Issue by vcntt** [hif2k1/battery_sim#107]
I have a question regarding the `utility_meter` component for `import_sensor` and `export_sensor`. In the documentation it statess it has to be _cummlatively (e.g. output of a utility_meter component)_. 

Since I received a warning on a decreased value I assume that the sensors cannot be reset. I am using utility meters that measure daily use, hence they reset every day.

**Comment by hif2k1** [comment]
Don't worry, you can just ignore the warning. Most people have a utility
meter that counts up continuously so it would be unexpected for it to ever
go down. In that case you'd want to know something wasn't working. However,
in your case it is expected behaviour. Maybe I should remove the warning.

**Comment by vcntt** [comment]
Maybe change it from warning to debug? Thank
