### ISSUE TITLE
Is there a way to reset the collected data (energy saved)?

### ISSUE THREAD

**Issue by Bascht74** [hif2k1/battery_sim#11]
![image](https://user-images.githubusercontent.com/66269310/148682997-424629e3-bfd9-46a7-b3a5-a57fed12facb.png)

I don't know where the data is stored / collected...

**Comment by hif2k1** [comment]
Hi there,

There isn't currently a way to reset this, but i have just updated the extension to add a daily, weekly and monthly counter so I hope this would provide the functionality you need. If you still need a reset function this could be added later.

Thanks,

**Comment by Bascht74** [comment]
Yes! I deleted the integration and everything is "0" + the new "start date" is available! Great job! Thx!
