### ISSUE TITLE
Wrong installation using HACS - using last release of both (HACS 1.19.2 and Battery_sim b52e8b6)

### ISSUE THREAD

**Issue by browetd** [hif2k1/battery_sim#12]
Problem with HACS installation:

Last release of battery_sim has been installed in the directory /config/custom_components/battery_sim/battery_sim
So HA is giving an error "Integration not found" ...

I moved the modules one level up, it is starting but I have lost all the data collected (energy saved) since a few weeks...

**Comment by browetd** [comment]
So If the problem was coming from HACS (not sure when I opened the issue), I am closing this one.

**Comment by hif2k1** [comment]
Yes, thanks for figuring this out. It seems to be this issue: https://github.com/hacs/integration/issues/2441 which I think has been fixed.
