### ISSUE TITLE
serveral issues with battery sim

### ISSUE THREAD

**Issue by RoyalFTH** [hif2k1/battery_sim#140]
Detected that custom integration 'battery_sim' calls async_forward_entry_setup for integration, battery_sim with title: battery_sim: HW Battery and entry_id: 01J1ZDQEMC6N4TSPDJ4AKDZFN6, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/battery_sim/__init__.py, line 137: hass.async_create_task(, please create a bug report at https://github.com/hif2k1/battery_sim/issues

Detected code that calls async_forward_entry_setup for integration battery_sim with title: battery_sim: HW Battery and entry_id: 01J1ZDQEMC6N4TSPDJ4AKDZFN6, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration battery_sim with title: battery_sim: 2,7kWh HW accu and entry_id: 01J26KNXMAZ3WF4PZ79G6HZWXC, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration battery_sim with title: battery_sim: 8,1kWh HW accu and entry_id: 01J26MW0M56F1XVV9HGRFN7W1R, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration battery_sim with title: battery_sim: 10,8kWh HW accu and entry_id: 01J26NBNXGFH9V8WNP5YTHR9K3, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Detected code that calls async_forward_entry_setup for integration battery_sim with title: battery_sim: 5,4kWh HW accu and entry_id: 01J29698G0Y8MWS3A3F0S8GQCJ, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by hif2k1** [comment]
Should be resolved
