### ISSUE TITLE
Simulated grid counters

### ISSUE THREAD

**Issue by JohanEikelenboom** [hif2k1/battery_sim#15]
FIrst of all, a great HA component, verry usefull to see if a home battery is worth buying.

I tried to add the new simulated grid counters to my energy dashboard and got the following error:
The following entities have state class 'measurement' but 'last_reset' is missing:
- sensor.<battery name>_simulated_grid_import_after_battery_discharging
- sensor.<battery name>_simulated_grid_export_after_battery_charging

Can you update the sensors so they have the "last_reset" property?

I'm running the latest version of Home Assistant (2022.2.3)

**Comment by JohanEikelenboom** [comment]
Another thing I noticed with the simulated sensors: They reset to the current import / export sensor values when Home Assistant reloads. This kind of messess up the energy tab.

**Comment by hif2k1** [comment]
These issues should be resolved in the latest update.
