### ISSUE TITLE
HA warning discharge/charge rate sensor  units are incorrect.

### ISSUE THREAD

**Issue by sprouse** [hif2k1/battery_sim#16]
I get a warning in my log file that looks like:
` sensor.tesla_powerwall_current_charging_rate has unit kW which is unsupported for device_class energy`

I think the cause is the units are in kW but the "energy" device_class expects "kWh".

**Comment by purcell-lab** [comment]
Charging rate sensors (kW) should be set to device_class power:

![image](https://user-images.githubusercontent.com/79175134/153781679-9a312d5f-33cd-40bb-bdbd-8c5d3844e259.png)

**Comment by hif2k1** [comment]
This should be resolved in the latest release. I hope this is now correct. Let me know if not.
