### ISSUE TITLE
battery_sim doesn't take the original unit_of_measurement of import_sensor/export_sensor into account

### ISSUE THREAD

**Issue by SirUli** [hif2k1/battery_sim#18]
Hi,

thanks for this extension - awesome work!

My import_sensor/export_sensors are reporting their values in Wh (ENERGY_WATT_HOUR) whereas battery_sim simply takes them as kWh (ENERGY_KILO_WATT_HOUR). While i could simply template the correct unit_of_measurement for battery_sim i would like to ask if you would want to take the unit_of_measurement of import_sensor/export_sensor into account?

Thanks in advance!

Best Regards,
Uli

**Comment by hif2k1** [comment]
This should be addressed in the latest release - acceptable units are Watt Hour and Kilowatt Hour. Hope this works for you, would be interested to know.

**Comment by SirUli** [comment]
Hi @hif2k1 

yes! This works - thank you so much, very much appreciated!

Cheers,
Uli
