### ISSUE TITLE
Calculate payback

### ISSUE THREAD

**Issue by littlbee** [hif2k1/battery_sim#21]
Great module, thanks !
Just wondering if there would be a way to calculate payback time for each battery model? 
If we could customize each battery by specifying its retail price, as well as electricity tariff, then calculating a battery payback time could be possible...
What do you think ?

**Comment by hif2k1** [comment]
Unfortunately, this is not going to be possible. The retail price is going to vary week to week never mind country to country. Also instillation costs are highly variable. I think you will have to work it out for yourself, but this should be fairly straight forward if you know how much energy you have saved.
