### ISSUE TITLE
% of spared energy import

### ISSUE THREAD

**Issue by littlbee** [hif2k1/battery_sim#22]
Would be great if, when configuring this add-on, we could specify (optionaly) which is the entity where we measure total imported monthly energy (imported from the grid). This way, each simulated battery could not just only show the total energy spared per month, but also how much % this is compared to the imported grid energy.

**Comment by hif2k1** [comment]
Thanks for this suggestion. I have been working on config flow, but this is a good idea. Would it just be percentage energy saved per month or would we need per day and week as well? Is it ok as an attribute or a separate sensor?

**Comment by littlbee** [comment]
I believe percentage saved per month would be good. This is at least how I have implemented it using custom sensors and templates:
![image](https://user-images.githubusercontent.com/12295362/163368329-63699ad7-1e65-4547-a242-6aad3b504625.png)

**Comment by littlbee** [comment]
Oh, and forgot to mention that as a attribute would be ok

**Comment by hif2k1** [comment]
I've just pushed an update which I hope works and would has this feature. It is an attribute of the simulated import sensor. Let me know if it is working as you expected.
