### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by Theredone51** [hif2k1/battery_sim#24]
In https://github.com/hif2k1/battery_sim/blob/master/README.md there's a typo in the example section. 
energy_tar**r**iff should be energy_tariff, otherwise HA will throw an error:
![image](https://user-images.githubusercontent.com/56741343/161764223-8381a676-3555-41d5-85f6-839f91f61892.png)

**Comment by hif2k1** [comment]
Readme updated - many thanks for flagging this up.
