### ISSUE TITLE
'Last reset' is missing

### ISSUE THREAD

**Issue by pdwonline** [hif2k1/battery_sim#26]
When I use this to simulate my car battery in the energy dashboard, I get a warning:

```
De volgende entiteiten hebben de statusklasse
'measurement' maar 'last_reset' ontbreekt

```

Translated to English this means that since this sensor is defined as class 'measurement' it is missiung the last_reset attribute

**Comment by hif2k1** [comment]
Hopefully this has resolved now in the recent release. If not do let me know.
