### ISSUE TITLE
Battery doesn't seem to be 'discharging' in HA

### ISSUE THREAD

**Issue by Theredone51** [hif2k1/battery_sim#27]
battery_sim version: beb6756
HA: 2022.4.2
Supervisor: Home Assistant OS 7.6

It seems like the battery does not 'discharge' when the state changes from charging to discharging. Only when the battery start charging again the next day, does the battery reset to 0.
![image](https://user-images.githubusercontent.com/56741343/162980948-25746a32-bcb8-435f-a7a2-d04ad6ec96da.png)
![image](https://user-images.githubusercontent.com/56741343/162980970-9ae39b3d-997b-4a3c-8c93-5da0f1369d02.png)

What it used to look like before:
![image](https://user-images.githubusercontent.com/56741343/162981465-25153036-0e14-4616-82c1-a6cd7a60aedd.png)

**Comment by hif2k1** [comment]
Are you getting any errors? I'm not sure that its resetting or just not
giving readings while it's discharging.

**Comment by hif2k1** [comment]
It looks like it charges and discharging ok at times e.g. on 4/10. Do you have a graph of the battery charge, import kWh and export kWh? How often does your energy meter update?

**Comment by Theredone51** [comment]
> 

It only seems that way, I've checked the 'discharging rate' and as you can see, since 4/05 it's no longer working / registering:
![image](https://user-images.githubusercontent.com/56741343/165284375-26ae0879-820d-4ae8-9184-15864db26562.png)

That date coincides with update 3535d7b for which I create a different issue on the same date:
https://github.com/hif2k1/battery_sim/issues/23

My energy meter updates every 30 minutes and the export sensor of the battery is set to work on the entity 'DailyElectricityReturned' which has remained functioning:
![image](https://user-images.githubusercontent.com/56741343/165285363-8cfa743f-4164-4493-aaea-f9a9e5fbd81b.png)

**Comment by hif2k1** [comment]
I've just pushed a new release which has debug logging in it. If you adjust your config to show debug info for battery sim then you should get some info in your logs and hopefully that might help to solve this puzzle. Thanks

**Comment by Theredone51** [comment]
> I've just pushed a new release which has debug logging in it. If you adjust your config to show debug info for battery sim then you should get some info in your logs and hopefully that might help to solve this puzzle. Thanks

This update (or the most recent HA updates) seems to have broken my setup completely, it's now not going up anymore either. I get following errors:
![image](https://user-images.githubusercontent.com/56741343/178667766-78ec0781-caef-4d16-bbd7-da7257cb3b9b.png)
![image](https://user-images.githubusercontent.com/56741343/178667830-2eca434d-b279-449f-a1fe-6842792174e3.png)
![image](https://user-images.githubusercontent.com/56741343/178667899-5ed0ad6c-d7ef-4155-8b5b-53ad5f97b169.png)
![image](https://user-images.githubusercontent.com/56741343/178667941-68fc72c8-55ca-4875-b6ae-eb691714c4a3.png)
![image](https://user-images.githubusercontent.com/56741343/178667991-77ef0240-3e1f-4fa3-8f12-2f6506c0dc6e.png)

**Comment by Theredone51** [comment]
Installed the latest update, recreated the battery and voila, it's working again:
![image](https://user-images.githubusercontent.com/56741343/181571659-2cc2ae5e-d4d0-4a1b-b27f-708c4e3b1569.png)
