### ISSUE TITLE
Feature request: Disable / pause (dis)charging

### ISSUE THREAD

**Issue by JohanEikelenboom** [hif2k1/battery_sim#29]
It would be nice to have a way to pause (dis)charging. The idea is that I want to pause discharging when I'm charging my electric car so that it doesn't drain the simulated battery.

The usecase would be that I create an automation to turn off discharging when my power usage is above 5 kW and start discharging again when the consumption is below 5 kW for 5 minutes.

**Comment by hif2k1** [comment]
I have just pushed a release which has a pause switch which should be able to be controlled by your automation. I hope it works, let me know any feedback.
