### ISSUE TITLE
update presented on hacs but no action when selected

### ISSUE THREAD

**Issue by eddysteurs** [hif2k1/battery_sim#32]
since this morning an update of this integration is presented on hacs but when you click on it nothing happens (other updates do work)

**Comment by TFhdKi95ae8L** [comment]
Same happened for me.
Workaround:
HACS->integrations->Battery sim->Click 3-dot setting menu right hand top screen-> redownload.

**Comment by hif2k1** [comment]
I'm not sure why this happened. It may have been because I have marked it as pre-release which I have now removed. Does this fix it?
