### ISSUE TITLE
Feature Request, using historical data?

### ISSUE THREAD

**Issue by dimitridelanghe** [hif2k1/battery_sim#38]
Would it be possible to use historical data?
Like most of us, we are using HA for a while and we are having history since the beginning of the energy update.
It would be nice, it's 1year data that could be very useful and the data is in the database.

**Comment by hif2k1** [comment]
Hi there, This is a great idea. I'm not sure how you access the data from the energy dashboard. I know how to access the data recorder for individual sensors. I'll have a look into it.

**Comment by hif2k1** [comment]
I'm afraid this is not going to be possible for me to do. If someone else has a better understanding of home assistant and can do so then that would be neat. Sorry.
