### ISSUE TITLE
Accept input from day and night meters

### ISSUE THREAD

**Issue by hif2k1** [hif2k1/battery_sim#42]
Some users have two different meters for day and night rates. At present the system only accepts one import and one export meter, but it would be food to permit at least two different meters to be supported.

**Comment by hif2k1** [comment]
This should now be functional although I've not been able to fully test as I don't have this type of meter.

**Comment by bolijndotme** [comment]
Hello,

Sorry for hijacking this issue, but it seems this is not entirely 'completed'. 
Let me know if you want me to open a new issue! 

I see it is now possible to add two meters for import (thank you for that!), but it is still not possible to have two meters to for export. I have two meters (2 for import and 2 for export) and in the summer i am returning energy to the grid in the early morning, so it would be great to have the option to add two meters for export as well. 

Thanks,
Michel

<img width="585" alt="Screenshot 2023-04-08 at 08 35 47" src="https://user-images.githubusercontent.com/43075336/230707426-8f6fdcb9-04f6-4cdc-ac79-cae78ea9a3c0.png">
