### ISSUE TITLE
money saved way out of loop

### ISSUE THREAD

**Issue by patraff** [hif2k1/battery_sim#43]
I installed the integration and inserted values into config with my local currency. The integration appears to be reading current data Ok except the value of money saved is clearly way off the mark. Otherwise I would buy 3 tesla powerwalls and retire.
See the snip from readings.
![battery sim](https://user-images.githubusercontent.com/40251343/188386079-a1608746-3ff8-459d-a998-95f66f3a7669.JPG)
Patrick

**Comment by hif2k1** [comment]
That's inflation for you mate. 
What is the tariff sensor reading? The money saved should literally just be the energy saved * the tariff. Is it a fixed tariff or does it vary through the day?

**Comment by patraff** [comment]
I can't see a tariff sensor. Sensors are
sensor.battery_sim_tesla_powerwall_current_charging_rate
sensor.battery_sim_tesla_powerwall_current_discharging_rate
sensor.battery_sim_tesla_powerwall_simulated_grid_export_after_battery_charging
sensor.battery_sim_tesla_powerwall_simulated_grid_import_after_battery_discharging
sensor.battery_sim_tesla_powerwall_total_energy_saved
sensor.battery_sim_tesla_powerwall_total_money_saved

pat

**Comment by hif2k1** [comment]
Sorry wasn't very clear. The tariff sensor is not part of the battery. When
you setup the battery you chose three sensors to use as inputs: import,
export and tariff. You must have picked something for the tariff input that
has a value of around 1900. You probably need to get rid of the battery and
make a new one with the right inputs. If you don't have a sensor setup that
represents your energy tariff just leave it blank.

**Comment by patraff** [comment]
I tried that but when I leave that field blank I get an error message

**Comment by hif2k1** [comment]
What's the error message? I probably need to fix something if you're
getting an error.
As a temporary measure you could make a helper with the value of your
energy tariff (price per kWh) and use that as the input.

**Comment by patraff** [comment]
I did send a pic of the error message. I tried a helper - just an input
number one. I put that in the field but essentially I get the same
overstated value.
I can't find any log file to send you from the integration.

**Comment by hif2k1** [comment]
Ok, thanks. I've reproduced the error creating a battery with no tariff meter and I think I've fixed it. I'm just testing it now for a day or so and then I'll release the fix. 

Using a helper with a value of 1 is still quite a high energy price - A$ 1 per kwh. The average in Australia is A$ 0.21 according to google so maybe try that in the mean time.

**Comment by patraff** [comment]
hi,
thanks for spending the time on this. Sorry my punctuation was a bit
lacking. When i said i created a helper, number one, i actually meant that
i created a helper of type 'number'. The value I entered was min .08 and
max .09 - energy companies here provide less value than you think😁

looking forward to the update.
Pat

**Comment by patraff** [comment]
I thought I would try again with whatever improvements you have made to the
code.
I completely deleted the battery sim folder in custom components -
restarted HA.
I then copied the full battery sim folder from github back into HA.
Then I tried to add 3 different battery types.
Sonnen, Tesla and LG chem.
It is night here so I was expecting nil values on all.
I have nil values on Sonnen and Lg chem but Tesla has populated with data
from somewhere even though the sensors used on each was exactly the same.
Here is a snip from my dashboard
 weird?

**Comment by hif2k1** [comment]
Sorry couldn't see the snip again - not sure why I can't see these. Has the error gone now when you try to make a battery without a tariff sensor?

The battery probably pre-populated from the data you had before as it would have the same name. This will persist in the home assistant database even after you delete the extension.

**Comment by patraff** [comment]
I'll see what happens on a full solar day. I currently have weird
exaggerated values on the tesla. Some overnight values on the Sonnen. Nil
values on the lg chem and the pika. I just put ina  custom battery,see if
that does anything different.
Might have to get in and clear the database?
Pat

**Comment by patraff** [comment]
So some further results for you.
I did a clean install of 3 sims
LGchem
Sonnen
Tesla
Both Lg and Sonnen are displaying quite similar values and look to be
matching my solar figures. the tesla is way off and does not vary its
display. I'll send the snip as a png file to see if that works.

**Comment by patraff** [comment]
All the sensor inputs were the same for all 3. Interesting that you mention
historical data as I have had all my historical data for the energy
dashboard disappear from prior to 01/10/22.
This was when i was making attempts to have the tesla battery display the
right data. I have decided at this point to opt out using battery sim as I
think the tesla one is somehow drawing on historical data but perhaps
corrupting my database somehow? I don't know but this is the only
integration installed in the last month and this is when problems arose.

**Comment by hif2k1** [comment]
ok, well thank you for trying to resolve the issue.
