### ISSUE TITLE
Status keeps at discharging

### ISSUE THREAD

**Issue by rickroetenberg** [hif2k1/battery_sim#44]
Hi,

The status keeps at discharging, but the current charging rate is above zero. So it's charging in my opinion

![image](https://user-images.githubusercontent.com/35991592/188895480-438f14da-6653-43d9-b231-59ed5d22ec8f.png)
![image](https://user-images.githubusercontent.com/35991592/188895546-363f0c26-1d0c-4f6f-8be3-1feb26b0026b.png)

**Comment by hif2k1** [comment]
Good spot. When I restructured the code I didn't re-implement this. Will fix shortly.

**Comment by hif2k1** [comment]
This should now be fixed.
