### ISSUE TITLE
HA restarts cause huge energy spikes

### ISSUE THREAD

**Issue by DutchessNicole** [hif2k1/battery_sim#45]
I've noticed in the last few days that whenever I restart HA either for an update of HAOS or for a HACS module, the battery sim integration gets reloaded with invalid data. This results in the battery suddenly having charged an obscene amount, and in the same time having discharged that same amount into the house. 

![Screenshot from 2022-09-10 13-06-10](https://user-images.githubusercontent.com/1487918/189480472-939b5b5f-fe32-45b1-a6c0-0076735da0b1.png)

Judging from the amount it adds on a restart there seems to be an issue with it adding sensor.battery_sim_6_0_kwh_battery_total_energy_saved to the daily counter. Total energy saved should of course not be added on a utility counter, I expect it's just there to keep track of the lifetime energy savings.

**Comment by DutchessNicole** [comment]
This is entirely repeatable, by the way. If I restart again, another spike appears.
![Screenshot from 2022-09-11 09-03-12](https://user-images.githubusercontent.com/1487918/189516217-b096417f-f2f0-4830-8273-8dbeb970f709.png)

**Comment by hif2k1** [comment]
I am looking into this. Initially I thought it the battery must be giving 0 readings immediately after restart, but it's not. I'm trying to reproduce the error now.

**Comment by hif2k1** [comment]
I've tried to reproduce this error, but I haven't been able to. What versions of HA and battery_sim are you using?

**Comment by mpepping** [comment]
Just removed the batterysim sensors from the energy dashboard because of this annoyance, but it was definitely an issue with HA 2022.9.6 (on hassos) /w v1.03 of batterysim. I believe even _since_ version v1.03.

**Comment by hif2k1** [comment]
Thanks for flagging this up. It must be giving 0 readings before the true
reading is reloaded making it look like a big increase. I'll try and fix it
when I can.

**Comment by hif2k1** [comment]
I think I have found a solution for this which is in the latest release. The sensors are now marked unavailable until they have a value and hopefully this will prevent the spikes.

**Comment by DutchessNicole** [comment]
Unfortunately this does not seem to fix the issue. battery sim version 1.07 still exhibits this behaviour during restarts, as I noticed today when performing an update to HAOS 2022.10.5.

Would it help to post some debug logs for the integration?

**Comment by hif2k1** [comment]
Yes debug would be helpful. It doesn't happen every restart so it's
difficult to track down. It hasn't happened to me yet with the latest
version despite a few restarts, but I'll keep looking into it.

There's quite a few similar bug reports with other energy metres and
extensions e.g.
https://community.home-assistant.io/t/data-spikes-in-the-energy-dashboard/469843
so it's not just battery sim.

**Comment by DutchessNicole** [comment]
Interesting that you'd say that it doesn't always happen. For me it happens every time HA restarts. 

```
2022-10-24 16:33:56.005 DEBUG (MainThread) [custom_components.battery_sim] Battery update event (battery_sim: 6.0_kWh_battery). Import: 0.004, Export: 0.0
2022-10-24 16:33:56.006 DEBUG (MainThread) [custom_components.battery_sim] Battery (battery_sim: 6.0_kWh_battery) normal mode.
2022-10-24 16:33:56.007 DEBUG (MainThread) [custom_components.battery_sim] Battery update complete (battery_sim: 6.0_kWh_battery). Sensors: {'total energy saved': 105.29, 'battery_energy_out': 105.29, 'battery_energy_in': 105.29, 'current charging rate': 0.0, 'current discharging rate': 0.0, 'simulated grid export after battery charging': 0.016, 'simulated grid import after battery discharging': 224.8289999999999, 'total_money_saved': 45.27, 'Battery_mode_now': 'Empty'}
```
This is what I see when I simply restart HA. Not a lot is happening but I do notice that both the `battery_energy_out` and `battery_energy_in` properties are set to what I assume is the value of `total energy saved`. Unfortunately debugging doesn't give any more info than this.

**Comment by hif2k1** [comment]
I think I might have managed to fix this now with the latest release.

**Comment by GentleJan** [comment]
looks like it is solved! great

**Comment by hif2k1** [comment]
Great, thanks!

**Comment by DutchessNicole** [comment]
Very nice! This works a treat. Thanks!
