### ISSUE TITLE
support force discharging

### ISSUE THREAD

**Issue by rickroetenberg** [hif2k1/battery_sim#46]
Support for force discharging as well. When investigating a dynamic energy contract can be sufficient if we can force to use the battery when the prices are high

**Comment by hif2k1** [comment]
Good idea, I'll try to include this in the next release

**Comment by hif2k1** [comment]
This is now available in the latest release although the money saved sensor will not be correct for this application and needs more work. Currently the battery_sim doesn't monitor export tariff at all so this needs some work.

**Comment by MathieuWuyts** [comment]
Any idea on when the export tariff would be fixed for this? I'm using the integration to simulate a battery charging an discharging on dynamic tariffs. Also, can you include a manual mode? This way the battery doesn't discharge automatically when using power from the grid, but only when I want it to discharge (when prices are high).

**Comment by hif2k1** [comment]
I've pushed it out today. I was trying to work on improving the config flow as it now has a lot of steps. Let me know if it works for you. I don't have these sort of tariffs so I've only tested it with simulated test data. Many thanks.
