### ISSUE TITLE
Can not find Battery Sim as Integration

### ISSUE THREAD

**Issue by thizmo** [hif2k1/battery_sim#47]
Dear hif2k1,

i really would love to have your sim in my homeassistant up and running since i want to have "real data" 
if in my installation a battery would make sense or not.

Unfortunately i can't find it via "Add integrations" nor on the the website for the integrations itself.
https://www.home-assistant.io/integrations/#search
And i don't want to install it manually, because i had to much trouble in the past with that.

So what am i doing wrong?
Running the latest:
- Home Assistant 2022.9.6

Thx a lot for your help.

**Comment by hif2k1** [comment]
Are you using HACS?

**Comment by thizmo** [comment]
> Are you using HACS?

Hi, i think i do not. Thanks for clearing that up.
Maybe you can highlight that more in your readme?

Think i did not recognize it on first sight....
