### ISSUE TITLE
Add status "Full" and "Empty"

### ISSUE THREAD

**Issue by twasietsmetjeroen** [hif2k1/battery_sim#48]
Is it possible to "Full" and "Empty" tot the status of the batteries? (or "Idle" as a combination of both)

**Comment by hif2k1** [comment]
Good idea. Currently it's a binary thing, but could be modified.

**Comment by hif2k1** [comment]
I have just released a new version with a mode indicator which can be charging, discharging, full, empty or paused/idle depending on what the battery is doing.
