### ISSUE TITLE
load balancer

### ISSUE THREAD

**Issue by Angelayes** [hif2k1/battery_sim#49]
Hello. i dont have any solar panels, and where i live i dont think solar is any good with the current prices.

what i wish you could intergrate in this is a spike balancer/ load balancer and also charge the battery from grid when prices are low and use power from battery when prices are high. Thanx :)

**Comment by hif2k1** [comment]
Hi there, you can already do this. Simply create an automation that turns on the "Override charging" function when the tariff reaches a certain level and turns it off again when the tariff rises again. This will force the battery to charge up at this time. The battery will automatically discharge when not in override mode. If you want you could also pause the battery when demand was low and only unpause it during a spike. However, these sort of home batteries are not good at dealing with spikes as they have quite limited discharge rates so can't usually provide big bursts of power e.g. to power a shower or something. Unless you have multiple tesla power walls or something I suppose.
What hasn't been implemented yet is working out the money saved during these operations - this is still a work in progress.
