### ISSUE TITLE
Efficiency calculation bug?

### ISSUE THREAD

**Issue by twasietsmetjeroen** [hif2k1/battery_sim#52]
Hi,

I was wondering if the efficiency is calculated right, I would expect that the "Energy saved" would differ to the "Energy in" sensor.
Using the data in my screenshots, I expect something like this:
"Energy in" * "Efficiency" = "Energy saved"
101,028 * 0,89 = 89,91492

![image](https://user-images.githubusercontent.com/14053822/203522030-751c2be5-11e8-42a7-a249-fcc4dd9c57c6.png)
![image](https://user-images.githubusercontent.com/14053822/203554700-c0779d88-8b4d-4284-9e43-b344317157f4.png)

**Comment by hif2k1** [comment]
This was a bug, but I think it has been fixed. Are you using the latest version? If so and it's still a problem let me know.

**Comment by twasietsmetjeroen** [comment]
I think I have the latest version 1.07, the images above are captured using this version.
![image](https://user-images.githubusercontent.com/14053822/204546536-e348e14b-cdbe-48b3-8f86-ec4bce7046aa.png)

**Comment by hif2k1** [comment]
Quite right sorry. I had fixed, but not uploaded the fix. Should be fixed now in 1.08

**Comment by twasietsmetjeroen** [comment]
Thank you, I've updated to 1.08 and tested it with an extra test battery. It is fixed!
