### ISSUE TITLE
Clarification on Import / Solar Feed

### ISSUE THREAD

**Issue by salty2011** [hif2k1/battery_sim#55]
Hello,

Reading through the documentation I am trying to understand how best to set up battery_sim, specifically how the "sensor.circuitsetup_cumulative_import_energy_kwh" is intended to be configured

Would this sensor just be all energy imported from the Grid I can measure or should it be accumulated between grid and solar production?

Currently my setup I have created an Import and Export sensor, the import strictly measure the import of power to the house. The export is the power that leaves the house (ie when solar is generating enough to cover the house consumption and can export)

**Comment by hif2k1** [comment]
That's right. Import should be energy coming into the house from the grid
not including energy coming from solar.

Essentially the battery sits between the house and the grid and doesn't
involve the solar directly. When the house is importing energy from the
grid the battery will discharge to reduce this import. When more energy is
being generated than used and is being exported to the grid then the
battery will take this up. So the two measurements we need are import and
export to and from the grid and the battery doesn't monitor solar
generation directly.

Hope that makes sense,

Hamish
