### ISSUE TITLE
Clarification for forced charge

### ISSUE THREAD

**Issue by mdeakin99** [hif2k1/battery_sim#56]
Hi

The battery started a ‘force charge’ last night at 2330 (as normal) but at some point in the night,  it filled up (as it does) and then started to discharge.

Does ‘force charge’ stay on until its manually switched off or does it disable after the battery is full? 

Is there a way to disable ‘discharge’ until a specific time?

I am trying to replicate charging during cheap rate and not discharging until cheap rate finishes.

**Comment by hif2k1** [comment]
It shouldn't start to discharge until the forced charging is disabled by
yourself or an automation. There is no mechanism to automatically switch
back. Was there a restart at all? I think that would reset it.

If it's a persistent problem let me know and I'll try to fix it.

**Comment by mdeakin99** [comment]
I think I may have restarted around that time so that’s highly possible.

Thanks… I should have thought about that

On 10 Jan 2023, at 19:18, hif2k1 ***@***.***> wrote:

﻿

It shouldn't start to discharge until the forced charging is disabled by
yourself or an automation. There is no mechanism to automatically switch
back. Was there a restart at all? I think that would reset it.

If it's a persistent problem let me know and I'll try to fix it.

**Comment by hif2k1** [comment]
Yes would welcome thoughts on this. Not sure if the battery should continue in a override charging or discharging state on a restart or not. HA could have been off for some time and circumstances may have changed so I think it makes sense to rever tot he default state if there is a restart.

**Comment by mdeakin99** [comment]
On the assumption that most people are force charging their simulated batteries and that most reboots would be during the day

Either 

A) Set it to discharge on reboot.  More than likely during the day and this would be the normal state
B) if you can,  restore to previous state. Only time this wouldn't be right is (I) HA been off for a long time -  they battery simulation for this cycle is incomplete anyway (ii) reboot happens during night to day rate shift.  Highly unlikely 

Just my thoughts on it though :)
