### ISSUE TITLE
2 kWh simulated grid export after battery charging (but nothing in battery and only 0,12 kWh from sun panels

### ISSUE THREAD

**Issue by GentleJan** [hif2k1/battery_sim#57]
As showing in image 3568 it show that there was 2 kWh between 09-10 simulated exported
But as you can see in image 3569 only 0,12 kWh was exported in real and as you can see in image 3570 my solar panels delivered 0,118 kWh and de simulated battery was "empty" (image 3571)
so the question is... why exported 2Kwh? No reboot or something like that was done
![IMG_3568](https://user-images.githubusercontent.com/59374422/212911700-0e194a5e-c777-42aa-84fd-d8a58ae75905.jpeg)
![IMG_3570](https://user-images.githubusercontent.com/59374422/212912623-ce253270-7130-4d07-8add-1f86046f41a4.jpeg)
![IMG_3569](https://user-images.githubusercontent.com/59374422/212913325-ca1c5fbe-6e35-41b2-9315-9743653b55a5.jpeg)
![IMG_3571](https://user-images.githubusercontent.com/59374422/212913735-03b505ca-f975-488e-8d8d-7dc854ea6f0e.jpeg)

**Comment by hif2k1** [comment]
It seems there are a lot of issues integrating with energy monitor probably
due to me not labelling sensors correctly in some way. Are you able to post
the graph of the "simulated grid export after battery charging" sensor? If
it has a big jump then there is a problem with the battery simulation, but
if not it is something to do with the energy monitor dashboard thinking the
sensor has reset for some reason when it hasn't.

**Comment by GentleJan** [comment]
![IMG_3575](https://user-images.githubusercontent.com/59374422/213377816-e59fac93-5bc0-457c-ae86-549f836f4cd6.jpeg)
Here by the graph of the simulated grid export after battery charging

**Comment by GentleJan** [comment]
No happened more than ones. …even just 3 hours ago

**Comment by hif2k1** [comment]
Is it always the first reading of the morning? Are there any warnings in the logs? 

It looks like you are using an export and import meter that is resetting each day. I wonder if that could be the reason? Is this the one connected to the battery sim? Is there a continuously increasing meter that you can use? The battery sim is meant to cope with meter resets, but it hasn't been extensively tested so it could be not working properly.

**Comment by hif2k1** [comment]
Closed as no response
