### ISSUE TITLE
Force charge not working 

### ISSUE THREAD

**Issue by mdeakin99** [hif2k1/battery_sim#58]
Hi

About 24hrs ago,  my battery sim stopped force charging.  Since then I have removed the battery,  rebooted and installed the battery again.

Any suggestions on how to troubleshoot?

**Comment by mdeakin99** [comment]
A further second reboot may have fixed it.  Will check to see if the automations work tonight.

**Comment by hif2k1** [comment]
Is it working now?

**Comment by mdeakin99** [comment]
Yep.  My bad,  didn’t reboot enough times
