### ISSUE TITLE
Entity money-saved is gone in latest 1.10 release

### ISSUE THREAD

**Issue by moorboss** [hif2k1/battery_sim#59]
After updating the sw version to 1.10 it turns out that the money-saved entity is gone in the inetegration. Eeverything else looks OK, but this item is not available anymore.

**Comment by hif2k1** [comment]
Have you got the "money saved on imports" and "money saved on exports". Any errors in the logs?

**Comment by moorboss** [comment]
In the past versions there was only 1 tariff applied, now it has been expanded, it doesn't seem to be backward compatible. Creating a new battery works, but then I loos my historical data, which I don't want, since I'm calculating the battery benefits over months now already. 
I don't have the sensors money saved on imports/exports
There is nog log entry showing an error on this.

**Comment by hif2k1** [comment]
Ok so it is a backwards compatibility issue. I will try and work out a fix.

**Comment by hif2k1** [comment]
Just published an update that hopefully fixes this for you.

**Comment by moorboss** [comment]
Unfortunately it is not solved, the total-money-saved entity is not available, also not in this modified 1.10 version.

**Comment by hif2k1** [comment]
Sorry, I'm not great at GitHub. The wrong files were uploaded. Should be working now.

**Comment by moorboss** [comment]
It is working now, nevertheless, the entities have been resetted to zero again...

**Comment by hif2k1** [comment]
Ah, sorry. I tried to get the fix done as quick as possible, but it must
have been too slow and the data from before the update expired
so it couldn't be restored.
