### ISSUE TITLE
Does adding battery to energy dashboard affect data

### ISSUE THREAD

**Issue by mdeakin99** [hif2k1/battery_sim#63]
Does adding the battery to the dashboard affect the quality of the data in Home Assistant?

I.e. If I add battery to dashboard will it affect my import/export stats to is the change purely visual?

**Comment by hif2k1** [comment]
If you add the battery to the dashboard and use the simulated import and
simulated export from the battery sim then it will affect the import/export
stats in the dashboard which are the only ones that persist long term in
home assistant. It won't affect the underlying meter sensors so if you log
them in some other way they will still be accurate, but they are purged
from the home assistant database after a certain number of days.
