### ISSUE TITLE
How should I use the data?

### ISSUE THREAD

**Issue by mdeakin99** [hif2k1/battery_sim#64]
Which are the good sensors to read/watch in order understand how much the battery would save me?

Currently I am calculating ROI on a battery by taking the battery (9.5kw) X 32p (the pence per kW saving by charging at night) and then figuring out how many days it will take to reach ROI.  Is there a sensor I should be checking instead?

**Comment by hif2k1** [comment]
Not quite sure I have enough details to answer your question, but I suppose
there are a couple of things to consider.

Battery sim is a real time simulation so you would need to run it for some
time to get an idea of how much energy you will save, but hopefully that
will be more accurate than the estimate you can make from just knowing the
size of the battery. Only by running the simulation over time can you work
out how much of the battery's potential charge/discharge capacity will be
used. You could set up an automation to force the battery to charge at
night and then allow it to discharge in the day. If you are doing this then
looking at the total energy saved will tell you hope much energy has gone
through the system and from that you can work out the saving.
Alternatively, you can set up the tariffs with your day and night or
constantly updated tariff and the battery sim will calculate the money
saved directly. If you have these set up then looking at the total money
saved would be the best sensor.

Hamish
