### ISSUE TITLE
Suggestion for improvement - modify the config without making a new battery

### ISSUE THREAD

**Issue by aboogerd** [hif2k1/battery_sim#65]
Hi,

Thanks for creating the battery sim. Nice add-on to simulate adding a battery to your system. Great job! 

One thing i'm missing is the option to modify the configuration, when you setup the battery from the HA intergration. Expecially checking and/or changing the energy tariff would be great. (something like HA did with the Energy dashbord settings. Option to select a entity or filling a fixed energy price)

Also the battery sim intergration is not showing in my HACS. I assume this had to do with the in hacs.json set country restriction. (i'm from the netherlands)

Thanks!! :-)

**Comment by hif2k1** [comment]
Thanks, I'll look into adding options to change the configuration afterwards.

I have removed the country specifier. Can you check if it is showing up in HACs now?

Thanks!.

**Comment by aboogerd** [comment]
Sorry for the delayed response. I can confirm the integration is now showing in the Dutch HACS. 

![image](https://user-images.githubusercontent.com/9293098/227458821-d7464e0a-9f43-40aa-942f-04ebcb04c672.png)

**Comment by rolandsteinmeyer** [comment]
Is there a way to change configuration in a text file somewhere in the meantime ? Have not found out where the config is stored  ....

**Comment by TheManoeuvre** [comment]
I second this, I set up 3 batteries via the UI and now I'm nolonger on a fixed tariff I think I'll have to ditch all the data for a YAML config. I presume I can use an entity state for this to change in the future? I'm thinking a number helper

**Comment by hif2k1** [comment]
Still in the pipeline. In the mean time you can edit the configuration by editing the file core.configentries which is in the hidden .storage directory in your home assistant config directory.

**Comment by hif2k1** [comment]
This should now be supported in the latest release
