### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by McWeis1** [hif2k1/battery_sim#66]
When I add the battery to the energy dashboard I get the following failure:

The following entities have the state class "measurement" but are missing "last_reset":
sensor.battery_sim_11_0_kwh_battery

The same failure appears when using a pre-defined battery.

**Comment by hif2k1** [comment]
Are you using the latest version of home assistant? I don't think this is
an issue in the latest version. If updating doesn't sort this or you ar
using the latest version let me know.

Thanks,

**Comment by McWeis1** [comment]
If I look into HACS it tells me I've downloaded the version 1.103. So I think, it's the latest version.

**Comment by hif2k1** [comment]
Sorry, not the latest version of battery_sim - the latest version of home assistant.

**Comment by McWeis1** [comment]
Sorry, my fault. version of home assistant is 2023.2.5

**Comment by hif2k1** [comment]
Sorry didn't follow this up. Is it still a problem? I don't get this error.

**Comment by McWeis1** [comment]
Hi, I also didn't look for this again, as the interesting thing for me is the amount I've saved with the battery.
From my side, we can close this topic.
