### ISSUE TITLE
Daily Stats

### ISSUE THREAD

**Issue by capqwerty** [hif2k1/battery_sim#7]
This might be a newbie question but here goes.

Is there a way to capture daily \ weekly graphs and stats?

**Comment by hif2k1** [comment]
I have added a daily, weekly and monthly energy saved counter in the latest release - update in HACS to get these. They are in the attributes of the batter sensor. If you would like more detail or graphs you could create a template sensor for the the energy saved. This code would need to be added to your config file.

```yaml
 - sensor:
      - name: total_energy_saved
        state: "{{ state_attr('sensor.tesla_powerwall', 'total_energy_saved) | float }}"
        unit_of_measurement: 'kWh'
