### ISSUE TITLE
Sensor request

### ISSUE THREAD

**Issue by Teunhen** [hif2k1/battery_sim#72]
For the simulation of the battery is it possible to have a sensor that counts everytime the battery is empty? Makes it easier to simulate multiple battery's of different sizes to see what you need to have installed in real life.

**Comment by hif2k1** [comment]
Hi there,

It is fairly easy to do this already - just create a counter helper and an
automation that triggers on the battery state being empty and uses the
increment service to increment the counter.

Hope that helps,

Hamish
