### ISSUE TITLE
request: add charging and discharging rates so it can be used in the energy dashboard.

### ISSUE THREAD

**Issue by aaamoeder** [hif2k1/battery_sim#9]
As the title says.
I'm using this but I'd love to integrate it into the energy dashboard, but for that I need a charging and discharging rate.
Would be awesome if this could be added !!!
Thanks for your work making this component

**Comment by joe98477** [comment]
Fantastic work on this component!!
This would have to be as separate entities?
Attributes would require a template sensor to integrate into the energy dashboard but either way having access to these values would be great for doing full simulations on energy management with different sized batteries.

**Comment by hif2k1** [comment]
I have just released an update that supports this so if you update the extension in HACS this should be visible for you. It is an attribute I'm afraid so you would need to add a template sensor. If a lot of people want this as an additional sensor this can be done, but I don't want to add loads of additional sensors that might just be confusing. Hope it works, let me know if there are any issues.

```yaml
  - sensor: 
      - name: rate_of_charge
        state: "{{ state_attr('sensor.tesla_powerwall', 'current_rate_of_charging_kw') | float }}"
        unit_of_measurement: 'kW'
 - sensor:
      - name: rate_of_discharge
        state: "{{ state_attr('sensor.tesla_powerwall', 'currrent_rate_of_discharging_kw') | float }}"
        unit_of_measurement: 'kW'

**Comment by aaamoeder** [comment]
hero !!! 🥇

**Comment by aaamoeder** [comment]
> 

one small remark...
You have made a small spelling mistake in the discharging attribute ... (3 r's)
