### ISSUE TITLE
Adding second battery

### ISSUE THREAD

**Issue by mikeykau** [hif2k1/battery_sim#93]
I'm trying to add a second battery, I saw that the readme says "Once you have done this you need to create your batteries. You can create any custom battery you want or use batteries with parameters the same as some common available models. The recommended way to do this is by going to **Settings > Devices and Services** and then clicking **Add Integration** and search for **Battery Simulation** and then work through the dialogue to create your battery. Repeat this process for each battery you want to add. "

If I try to repeat the process it says "This device is already configured."

**Comment by mikeykau** [comment]
I've worked it out, used the option of custom battery for the second battery.

**Comment by hif2k1** [comment]
Sorry yes, the issue is you can't have two batteries with the same name.
They can be identical in other respects.
