### ISSUE TITLE
Balancing two batteries

### ISSUE THREAD

**Issue by mikeykau** [hif2k1/battery_sim#94]
This is more of a how to question.
I want to simulate two Powerwalls.
I set them both up, but when my house is consuming 6kW, both batteries discharge at 5kW, with the simulated grid being 1kW.
It should instead show 3kW coming from each battery in this scenario, and zero from grid.
Is it possible I have configured something wrong?

**Comment by hif2k1** [comment]
The two batteries don't know about each other. This is important so you can
simulate multiple battery options at the same time and see how much each
one would save you without them competing. If you want to simulate 2 power
walls you should create a single custom battery with twice the capacity,
charge  and discharge rates of a single power wall.
